version: '3.8'

services:
  backend:
    build: .
    container_name: peer_review_backend
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:backend
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/RevisionPares
    depends_on:
      - mongo


  mongo:
    image: mongo:latest
    container_name: peer_review_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  frontend:
    build: .
    container_name: peer_review_frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    # El flag --host es importante en Vite para que permita conexiones externas al contenedor
    command: npm run dev -- --host 0.0.0.0
    environment:
      - VITE_PORT=5173
      - BACKEND_URL=http://backend:3000
    depends_on:
      - backend

volumes:
  mongo_data:
