-- AlterTable
ALTER TABLE `papers` MODIFY `status` ENUM('RECEIVED', 'UNDER_REVIEW', 'MINOR_CHANGES', 'MAJOR_CHANGES', 'ACCEPTED', 'REJECTED', 'COMPLETED') NOT NULL DEFAULT 'RECEIVED';

-- AlterTable
ALTER TABLE `users` ADD COLUMN `isGlobalAdmin` BOOLEAN NOT NULL DEFAULT false;
